GET http://localhost:3000/peliculas HTTP/1.1
###
GET http://localhost:3000/peliculas/3 HTTP/1.1

###
POST http://localhost:3000/peliculas HTTP/1.1
Content-Type: application/json

{
    "id" : 8,
    "Titulo": "El dia despues de mañana",
    "Director": "Emi ",
    "actores": "Woopi Goldelberg"

}

###
PUT http://localhost:3000/peliculas/4 HTTP/1.1
Content-Type: application/json

{
   "Titulo": "ET"
}

###
DELETE http://localhost:3000/peliculas/1 HTTP/1.1